package com.lotelab.analizador;
import android.app.*;import android.os.*;import android.view.*;import android.widget.*;
public class MejorasActivity extends Activity{
TextView txtVersiones;
@Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_mejoras);
txtVersiones=findViewById(R.id.txtVersiones);
findViewById(R.id.btnVolver).setOnClickListener(v->finish());
txtVersiones.setText(construirTexto());
}
String construirTexto(){
StringBuilder s=new StringBuilder();
s.append("═══════════════════════════\n");
s.append("   ANALIZADOR DE LOTERIA\n");
s.append("   Pick 3 · Pick 4 Florida\n");
s.append("═══════════════════════════\n\n");
s.append("── v3.3 — Menú lateral ──\n");
s.append("• Menú lateral deslizable (☰)\n");
s.append("• Todos los botones movidos al menú\n");
s.append("• AndroidX activado\n");
s.append("• Organización por secciones:\n");
s.append("    - Consultas\n");
s.append("    - Análisis\n");
s.append("    - Datos\n");
s.append("    - Info\n\n");
s.append("── v3.2e — Fix Estab y Decenas ──\n");
s.append("• Fix: ordenar Parlets por Estabilidad\n");
s.append("• Fix: Decenas = Fijo / 10\n");
s.append("• Fix: Unidades = Fijo % 10\n");
s.append("• Estab calculada solo Top 100 parlets\n");
s.append("• try/catch muestra errores en pantalla\n\n");
s.append("── v3.2d — Paginación ──\n");
s.append("• Paginación de Parlets (200 por página)\n");
s.append("• Botones ◀ ▶ 🏠 ⏭ en Parlets\n");
s.append("• Contador de página\n");
s.append("• Cálculo en hilo de fondo\n\n");
s.append("── v3.2c — Estabilidad ──\n");
s.append("• Fórmula de estabilidad (CV de intervalos)\n");
s.append("• Colores: verde/amarillo/azul/gris\n");
s.append("• Guardar CSV de estadísticas\n");
s.append("• 6 categorías: Números, Centenas, Decenas, Unidades, Dígitos, Parlets\n\n");
s.append("── v3.2b — Categorías ──\n");
s.append("• 6 categorías de análisis estadístico\n");
s.append("• Frecuencia relativa (1/X)\n");
s.append("• Filtros por posición\n\n");
s.append("── v3.2a — Por período ──\n");
s.append("• Estadísticas por rango de fechas\n");
s.append("• Análisis de Números\n\n");
s.append("── v3.1 — Predicciones ──\n");
s.append("• Guardar predicción de hoy\n");
s.append("• Validación automática al importar\n");
s.append("• Ver mis predicciones\n\n");
s.append("── v2.9 — Centenas ──\n");
s.append("• Centenas como categoría propia\n\n");
s.append("── v2.8 — Historial ──\n");
s.append("• Historial estilo Lucky Strike\n");
s.append("• Paginación del historial\n\n");
s.append("── v2.7 — Buscar números ──\n");
s.append("• Búsqueda por Números (00-99)\n");
s.append("• Búsqueda por Decenas (0-9)\n");
s.append("• Búsqueda por Terminales (0-9)\n\n");
s.append("── v2.6 — Buscar días ──\n");
s.append("• Búsqueda por días específicos\n");
s.append("• Atajos por rango del mes\n\n");
s.append("── v2.5 — Análisis base ──\n");
s.append("• Tops por rango del mes (1-5, 6-10, ...)\n");
s.append("• Calientes y Fríos (histórico y reciente)\n");
s.append("• Sesgos de Decenas y Terminales\n");
s.append("• Centenas calientes y frías\n");
s.append("• Combinaciones Dec×Term\n");
s.append("• Backtesting\n\n");
s.append("── v1-v2 — Base ──\n");
s.append("• Importar historial (TSV, CSV, XLSX, DOCX)\n");
s.append("• Agregar sorteo manual\n");
s.append("• Exportar CSV\n");
s.append("• Base de datos SQLite\n");
s.append("• Análisis por rangos del mes\n\n");
s.append("═══════════════════════════\n");
s.append("Total: 3461 sorteos\n");
s.append("Desde enero 2022 hasta hoy\n");
s.append("═══════════════════════════\n");
return s.toString();
}
}
